#!/usr/bin/env python3
"""
Voice-WebBuilder-Agent — Page Generator
========================================
Generates a live website based on:
1. page-content.json — content collected from voice conversation
2. site/photos/ — photos uploaded from phone

Uses Anthropic API (single call) → writes index.html → git push → Vercel auto-deploy.

Run:
    python3 modify-site.py

Requires:
    export ANTHROPIC_API_KEY="sk-ant-..."
    page-content.json (created by webhook-server.py)
"""

import os
import sys
import json
import subprocess
from datetime import datetime

try:
    import anthropic
except ImportError:
    print("[ERROR] Missing 'anthropic' package. Run: pip install anthropic")
    sys.exit(1)

# Paths — relative to repo
PIPELINE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(PIPELINE_DIR)
INDEX_PATH = os.path.join(REPO_ROOT, "site", "index.html")
PHOTOS_DIR = os.path.join(REPO_ROOT, "site", "photos")
CONTENT_FILE = os.path.join(PIPELINE_DIR, "page-content.json")


def get_photo_filenames():
    """Returns list of photo filenames in site/photos/."""
    if not os.path.exists(PHOTOS_DIR):
        return []
    return sorted([f for f in os.listdir(PHOTOS_DIR)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp'))])


def build_prompt(page_content, photo_filenames):
    """Builds the Anthropic API prompt with dynamic content."""

    now = datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    photos_section = ""
    if photo_filenames:
        photo_list = "\n".join([f"- photos/{f}" for f in photo_filenames])
        photos_section = f"""
LIVE PHOTOS (uploaded during the event):
Display a photo gallery at the top of the page. Files are in photos/:
{photo_list}

Use <img src="photos/FILENAME"> for each photo.
Display in a grid with rounded corners, below the title.
Add caption: "Live photos — uploaded during the event".
"""

    return f"""Create a COMPLETE HTML page based on the description below.

PAGE DESCRIPTION (collected from a voice conversation):
{page_content}

{photos_section}

CONTENT STYLE:
- Informational, professional, factual
- NO marketing language, NO hype, NO self-promotion
- NO words like "revolutionary", "groundbreaking", "innovative", "cutting-edge"
- Write like a journalist or encyclopedia — present facts clearly
- Let the content speak for itself

TECHNICAL REQUIREMENTS:
- Use Tailwind CSS (CDN: https://cdn.tailwindcss.com)
- Dark theme: background #1A1A1A, text #FAFAF5, accent #E8B931
- Font: Inter (Google Fonts)
- Responsive — mobile first
- Style: modern, clean, professional
- Single HTML file, everything inline
- At the very bottom, footer with TWO lines:
  Line 1: "This page was generated live by a voice AI agent"
  Line 2: "Generated: {timestamp}" (use this exact timestamp)

PAGE STRUCTURE:
1. Header with page title
2. Photo gallery (if photos available)
3. Main content — organized by topic from the description
4. Additional details (if provided)
5. Footer with generation timestamp

IMPORTANT: Return a COMPLETE index.html file, ready to save.
No comments, no explanations, no markdown code fences — ONLY raw HTML.
"""


def main():
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("[ERROR] Missing ANTHROPIC_API_KEY environment variable!")
        sys.exit(1)

    print(f"[1/5] Reading page-content.json...")
    if os.path.exists(CONTENT_FILE):
        with open(CONTENT_FILE, "r", encoding="utf-8") as f:
            content_data = json.load(f)
        page_content = content_data.get("page_content", "A live event page")
        print(f"       Content: {page_content[:150]}...")
    else:
        print(f"[WARN] No {CONTENT_FILE} — using default content")
        page_content = "A live event page generated by AI voice agent."

    photo_filenames = get_photo_filenames()
    print(f"[2/5] Found {len(photo_filenames)} photos: {photo_filenames}")

    prompt = build_prompt(page_content, photo_filenames)

    print(f"[3/5] Sending to Anthropic API (claude-sonnet-4-20250514)...")
    client = anthropic.Anthropic()

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=16000,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    new_html = message.content[0].text

    # Strip markdown code fences if present
    if new_html.startswith("```html"):
        new_html = new_html[7:]
    if new_html.startswith("```"):
        new_html = new_html[3:]
    if new_html.endswith("```"):
        new_html = new_html[:-3]
    new_html = new_html.strip()

    print(f"[4/5] Writing new index.html ({len(new_html)} chars)...")
    with open(INDEX_PATH, "w", encoding="utf-8") as f:
        f.write(new_html)

    # Git push — add both HTML and photos
    print("[5/5] Git push...")
    try:
        subprocess.run(["git", "add", "site/"], cwd=REPO_ROOT, check=True)
        subprocess.run(
            ["git", "commit", "-m",
             f"Live: page generated by voice AI agent ({datetime.now().strftime('%Y-%m-%d %H:%M')})"],
            cwd=REPO_ROOT,
            check=True
        )
        subprocess.run(["git", "push"], cwd=REPO_ROOT, check=True)
        print("[DONE] Success! Vercel will deploy in ~30 sec.")
    except subprocess.CalledProcessError as e:
        print(f"[GIT ERROR] {e}")
        print("[HINT] Check that git remote is set and you have push access.")
        sys.exit(1)


if __name__ == "__main__":
    main()
