#!/usr/bin/env python3
"""
Voice-WebBuilder-Agent — Webhook Server
========================================
Listens on localhost:5555. Receives voice agent output
and triggers page generation + deploy via git push.

Endpoints:
    POST /modify-website  — called by voice agent tool (with page_content)
    GET  /upload           — photo upload page (mobile-friendly)
    POST /upload           — receives photos
    GET  /photos-list      — list of uploaded photos (JSON)
    GET  /status           — is generation running?
    GET  /trigger          — manual trigger (fallback)

Run:
    cd pipeline && python3 webhook-server.py
"""

from flask import Flask, request, jsonify, send_from_directory
import subprocess
import threading
import os
import json
import time
from datetime import datetime

app = Flask(__name__)

# Paths — relative to repo root
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODIFY_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "modify-site.py")
PHOTOS_DIR = os.path.join(REPO_ROOT, "site", "photos")
CONTENT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "page-content.json")

os.makedirs(PHOTOS_DIR, exist_ok=True)

is_running = False


def run_modification():
    """Runs the page generation script in a background thread."""
    global is_running
    is_running = True
    try:
        result = subprocess.run(
            ["python3", MODIFY_SCRIPT],
            capture_output=True,
            text=True,
            timeout=180
        )
        print(f"[MODIFY] stdout: {result.stdout}")
        if result.returncode != 0:
            print(f"[MODIFY] stderr: {result.stderr}")
    except subprocess.TimeoutExpired:
        print("[MODIFY] TIMEOUT — script took too long")
    except Exception as e:
        print(f"[MODIFY] ERROR: {e}")
    finally:
        is_running = False


def get_photo_list():
    """Returns list of photo filenames."""
    if not os.path.exists(PHOTOS_DIR):
        return []
    return sorted([f for f in os.listdir(PHOTOS_DIR)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp'))])


@app.route("/modify-website", methods=["POST"])
def modify_website():
    """Endpoint called by voice agent tool.
    Receives page_content — description collected from voice conversation."""
    global is_running

    if is_running:
        return jsonify({
            "status": "already_running",
            "message": "Generation already in progress, please wait."
        }), 200

    data = request.get_json(silent=True) or {}
    page_content = data.get("page_content", "A live event page generated by voice agent")

    print(f"[WEBHOOK] Received page_content: {page_content[:200]}...")

    content_data = {
        "page_content": page_content,
        "timestamp": datetime.now().isoformat(),
        "photos": get_photo_list()
    }
    with open(CONTENT_FILE, "w", encoding="utf-8") as f:
        json.dump(content_data, f, ensure_ascii=False, indent=2)

    thread = threading.Thread(target=run_modification)
    thread.start()

    return jsonify({
        "status": "started",
        "message": "Page generation started. The site will be ready in ~30-40 seconds."
    }), 200


@app.route("/upload", methods=["GET"])
def upload_page():
    """Mobile-friendly photo upload page."""
    photos = get_photo_list()
    photo_count = len(photos)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Photos — Voice WebBuilder</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, system-ui, sans-serif;
            background: #1A1A1A; color: #FAFAF5;
            min-height: 100vh; padding: 20px;
            display: flex; flex-direction: column; align-items: center;
        }}
        h1 {{ font-size: 1.4em; margin-bottom: 8px; color: #E8B931; }}
        .subtitle {{ color: #999; margin-bottom: 24px; font-size: 0.9em; }}
        .upload-btn {{
            display: block; width: 100%; max-width: 400px;
            padding: 20px; margin: 10px 0;
            background: #E8B931; color: #1A1A1A;
            border: none; border-radius: 12px;
            font-size: 1.2em; font-weight: 700;
            cursor: pointer; text-align: center;
        }}
        .upload-btn:active {{ background: #d4a62c; transform: scale(0.98); }}
        .status {{
            margin-top: 16px; padding: 12px 20px;
            border-radius: 8px; font-size: 0.95em;
            display: none; width: 100%; max-width: 400px; text-align: center;
        }}
        .status.success {{ display: block; background: #2d4a2d; color: #7fef7f; }}
        .status.error {{ display: block; background: #4a2d2d; color: #ef7f7f; }}
        .status.uploading {{ display: block; background: #3d3d1a; color: #E8B931; }}
        .photo-count {{
            margin-top: 20px; padding: 10px 20px;
            background: #2a2a2a; border-radius: 8px;
            color: #999; font-size: 0.9em;
        }}
        .preview {{
            margin-top: 16px; max-width: 400px; width: 100%;
            display: flex; flex-wrap: wrap; gap: 8px; justify-content: center;
        }}
        .preview img {{
            width: 80px; height: 80px; object-fit: cover;
            border-radius: 8px; border: 2px solid #333;
        }}
        input[type="file"] {{ display: none; }}
    </style>
</head>
<body>
    <h1>Voice WebBuilder</h1>
    <p class="subtitle">Upload photos for your live site</p>

    <input type="file" id="fileInput" accept="image/*" capture="environment">
    <button class="upload-btn" onclick="document.getElementById('fileInput').click()">
        Take Photo
    </button>

    <input type="file" id="fileInputGallery" accept="image/*" multiple>
    <button class="upload-btn" style="background:#444;color:#FAFAF5"
            onclick="document.getElementById('fileInputGallery').click()">
        Choose from Gallery
    </button>

    <div id="status" class="status"></div>
    <div class="photo-count">Uploaded photos: <strong id="count">{photo_count}</strong></div>
    <div class="preview" id="preview"></div>

    <script>
        const statusEl = document.getElementById('status');
        const countEl = document.getElementById('count');
        const previewEl = document.getElementById('preview');

        function uploadFile(file) {{
            statusEl.className = 'status uploading';
            statusEl.textContent = 'Uploading...';

            const formData = new FormData();
            formData.append('photo', file);

            fetch('/upload', {{ method: 'POST', body: formData }})
                .then(r => r.json())
                .then(data => {{
                    if (data.status === 'ok') {{
                        statusEl.className = 'status success';
                        statusEl.textContent = 'Saved! (' + data.filename + ')';
                        countEl.textContent = data.total_photos;
                        const img = document.createElement('img');
                        img.src = '/photos/' + data.filename;
                        previewEl.appendChild(img);
                    }} else {{
                        statusEl.className = 'status error';
                        statusEl.textContent = 'Error: ' + data.error;
                    }}
                }})
                .catch(err => {{
                    statusEl.className = 'status error';
                    statusEl.textContent = 'Connection error';
                }});
        }}

        document.getElementById('fileInput').addEventListener('change', function(e) {{
            if (e.target.files[0]) uploadFile(e.target.files[0]);
        }});

        document.getElementById('fileInputGallery').addEventListener('change', function(e) {{
            Array.from(e.target.files).forEach(uploadFile);
        }});

        fetch('/photos-list')
            .then(r => r.json())
            .then(photos => {{
                photos.forEach(name => {{
                    const img = document.createElement('img');
                    img.src = '/photos/' + name;
                    previewEl.appendChild(img);
                }});
            }});
    </script>
</body>
</html>"""


@app.route("/upload", methods=["POST"])
def upload_photo():
    """Receives photo upload."""
    if "photo" not in request.files:
        return jsonify({"status": "error", "error": "No file"}), 400

    photo = request.files["photo"]
    if photo.filename == "":
        return jsonify({"status": "error", "error": "Empty file"}), 400

    existing = get_photo_list()
    next_num = len(existing) + 1
    ext = os.path.splitext(photo.filename)[1].lower() or ".jpg"
    filename = f"photo-{next_num:03d}{ext}"
    filepath = os.path.join(PHOTOS_DIR, filename)

    photo.save(filepath)
    print(f"[UPLOAD] Saved: {filepath} ({os.path.getsize(filepath)} bytes)")

    return jsonify({
        "status": "ok",
        "filename": filename,
        "total_photos": len(get_photo_list())
    })


@app.route("/photos/<filename>")
def serve_photo(filename):
    """Serves photos for preview."""
    return send_from_directory(PHOTOS_DIR, filename)


@app.route("/photos-list", methods=["GET"])
def photos_list():
    """Returns photo list as JSON."""
    return jsonify(get_photo_list())


@app.route("/status", methods=["GET"])
def status():
    """Check if generation is running."""
    return jsonify({
        "is_running": is_running,
        "photos": len(get_photo_list())
    })


@app.route("/trigger", methods=["GET"])
def manual_trigger():
    """Manual trigger from browser (fallback plan)."""
    global is_running

    if is_running:
        return "<h1>Generation already running...</h1>", 200

    if not os.path.exists(CONTENT_FILE):
        content_data = {
            "page_content": "A live event page — generated by voice AI agent on stage.",
            "timestamp": datetime.now().isoformat(),
            "photos": get_photo_list()
        }
        with open(CONTENT_FILE, "w", encoding="utf-8") as f:
            json.dump(content_data, f, ensure_ascii=False, indent=2)

    thread = threading.Thread(target=run_modification)
    thread.start()

    return "<h1>Triggered! Page generation started.</h1>", 200


if __name__ == "__main__":
    print("=" * 60)
    print("  VOICE-WEBBUILDER-AGENT — Webhook Server")
    print("=" * 60)
    print(f"  Repo root:       {REPO_ROOT}")
    print(f"  Photos dir:      {PHOTOS_DIR}")
    print(f"  Modify script:   {MODIFY_SCRIPT}")
    print()
    print(f"  Webhook:         http://localhost:5555/modify-website")
    print(f"  Upload photos:   http://localhost:5555/upload")
    print(f"  Manual trigger:  http://localhost:5555/trigger")
    print(f"  Status:          http://localhost:5555/status")
    print("=" * 60)
    app.run(host="0.0.0.0", port=5555, debug=False)
